version: '3.8'

services:
  web:
    build:
      context: .
    image: inventorydemo_web_docker_env
    container_name: inventorydemo_web
    depends_on:
      - postgres-dev
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.webapp
    volumes:
      - ./:/app

  # mysqldb:
  #   image: mysql
  #   ports:
  #     - 3306:3306
  #   environment: 
  #     - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  #   volumes:
  #     - mysql:/var/lib/mysql
  #     - mysql_config:/etc/mysql

  postgres-dev:
    image: postgres
    container_name: postgres-dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=2651457d2882970e8d37738254173ca03839c1f14314dcaa4c6b501529379ab6
      - POSTGRES_USER=ytkjwekbsvhpng
      - POSTGRES_DB=d87gbe1ta420fb
    volumes:
       - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  # mysql:
  # mysql_config:
  